theme: minima
title: Github blog
author: Einoven
email: nvaidya@rdc.com
description: > # this means to ignore newlines until "baseurl:"
  No awesome description to write at this moment. Will add this later buy in _config.yml. 
  It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
twitter_username: no twitter
github_username:  einoven

show_excerpts: true # set to false to remove excerpts on the homepage
